server:
  port: 9090

spring:
  kafka:
#    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    bootstrap-servers: localhost:9092
#    security:
#      protocol: ${SECURITY_PROTOCOL}
#    properties:
#      sasl:
#        mechanism: ${SASL_MECHANISM}
#        jaas:
#          config: ${SASL_JAAS_CONFIG}
